// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ntbdgaqpecsynmhmtobb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50YmRnYXFwZWNzeW5taG10b2JiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY0MDE2NDAsImV4cCI6MjA4MTk3NzY0MH0.0KDs4lPEYNQb2DzBrfIFnLiayOYq436QYZcZRmPDULg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);